seed: 0
discount: 0.99
num_unroll_steps: 2
num_td_steps: 100
num_stacked_frames: 1

env:
  name: MinAtar:Seaquest-v1
  known_bound_min: 0
  known_bound_max: 1

replay:
  use_remote: true
  max_size: 1_000_000
  min_size: 1_000
  prefetch_max_size: 1_000
  decay: 0.99
  sampling_strategy: uniform
  num_unroll_steps: ${num_unroll_steps}
  num_td_steps: ${num_td_steps}
  num_stacked_frames: ${num_stacked_frames}
  discount: ${discount}

param_opt:
  use_remote: true
  num_gpus: 0.5
  save_dir: ./save/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: 10
    obs_cols: 10
    obs_channels: 6
    repr_rows: 10
    repr_cols: 10
    repr_channels: 6
    dim_action: 6
    repr_tower_blocks: 6
    repr_tower_dim: 6
    pred_tower_blocks: 6
    pred_tower_dim: 6
    dyna_tower_blocks: 6
    dyna_tower_dim: 6
    dyna_state_blocks: 6

mcts:
  known_bound_min: ${env.known_bound_min}
  known_bound_max: ${env.known_bound_max}
  dirichlet_alpha: 0.2
  frac: 0.2

train:
  num_epochs: 200
  epoch_train_start: 2
  # TODO: make ratio-based
  num_batches_per_epoch: 64
  batch_size: 256
  lr: 5.0e-3
  weight_decay: 5.0e-2

  env_workers:
    num_workers: 6
    num_ticks_per_epoch: 20
    num_envs: 1
    num_universes: 50
    num_cpus: 1
    num_gpus: 1

  reanalyze_workers:
    num_workers: 0
    num_universes: 50
    num_trajs: 1

test:
  num_universes_per_env_worker: 50
  num_universes_per_reanalyze_worker: 20
  num_trajs_per_reanalyze_universe: 2
  test_interval: 5
