seed: 0
discount: 1
num_unroll_steps: 5
num_td_steps: 1000
history_length: 1
dim_action: auto
debug: false

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: auto
  num_cols: auto
  num_channels: auto
  num_players: auto

replay:
  num_shards: 6
  kwargs:
    max_trajs_size: 4_000
    max_targets_size: 500_000
    sampling_strategy: uniform
    num_unroll_steps: ${num_unroll_steps}
    num_td_steps: ${num_td_steps}
    history_length: ${history_length}
    discount: ${discount}
    decay: 0.99
    save_dir: ./replay/

scalar_transform:
  support_min: -30
  support_max: 30
  eps: 1.0e-3
  contract: true

param_opt:
  num_gpus: 0.6
  save_interval: 10
  save_dir: ./checkpoints/
  load_from: null

nn:
  arch_cls: ResNetV2Architecture
  spec_cls: ResNetV2Spec
  spec_kwargs:
    history_length: ${history_length}
    num_players: ${env.num_players}
    frame_rows: ${env.num_rows}
    frame_cols: ${env.num_cols}
    frame_channels: ${env.num_channels}
    dim_action: ${dim_action}
    repr_rows: ${env.num_rows}
    repr_cols: ${env.num_cols}
    repr_channels: 32
    repr_tower_blocks: 6
    pred_tower_blocks: 2
    dyna_tower_blocks: 2
    dyna_state_blocks: 2

train:
  num_epochs: 500
  update_step_ratio: 20
  batch_size: 2048
  lr: 2.0e-2
  weight_decay: 1.0e-4
  target_update_period: 100
  min_targets_to_train: 10_000
  consistency_loss_coef: 2.0

training_worker:
  num_workers: 32
  num_envs: 32
  num_cpus: 1
  num_gpus: 0.1
  num_steps: 50
  update_period: 5
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    max_depth: ${num_unroll_steps}
    num_simulations: 16
    search_type: "gumbel_muzero"
    kwargs:
      gumbel_scale: 1.0
      max_num_considered_actions: 4
    # kwargs:
    #   dirichlet_alpha: 0.5
    #   dirichlet_fraction: 0.25
    #   temperature: 1.0
    #   pb_c_init: 1.25

testing_worker:
  # kinds: ['tournament', 'trajectory']
  num_workers: 0
  num_cpus: 1
  num_gpus: 0.1
  model: NNModel
  num_steps: 25
  update_period: 1
  test_period: 10
  planner: ${training_worker.planner}
    # dim_action: ${dim_action}
    # discount: -1.0
    # max_depth: ${num_unroll_steps}
    # num_simulations: 16
    # use_gumbel: true
    # kwargs:
    #   gumbel_scale: 1.0
    #   max_num_considered_actions: 6

reanalyze_worker:
  num_workers: 0
  num_envs: 32
  num_cpus: 1
  num_gpus: 0.1
  num_steps: 100
  update_period: 1
  planner:
    dim_action: ${dim_action}
    discount: -1.0
    max_depth: ${num_unroll_steps}
    num_simulations: 25
    kwargs:
      dirichlet_alpha: 0.1
      dirichlet_fraction: 0.1
      pb_c_init: 1.75

vis:
  load:
    pkl: null
    run: null
  show:
    tree: true
    projection: false
  num_steps: 25
  planner:
    dim_action: ${dim_action}
    discount: -1.0
    max_depth: ${num_unroll_steps}
    num_simulations: 256
    kwargs:
      dirichlet_alpha: 0.5
      dirichlet_fraction: 0.25
      temperature: 1.0
      pb_c_init: 1.25
