seed: 0
discount: 0.997
num_unroll_steps: 5
num_td_steps: 5
# TODO: rename num_stakd_frames to history_len or something
num_stacked_frames: 4
dim_action: 5
debug: false

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: 10
  num_cols: 10
  num_channels: 6

replay:
  use_remote: true
  max_trajs_size: 500_000
  max_targets_size: 1_000_000
  sampling_strategy: value_diff
  num_unroll_steps: ${num_unroll_steps}
  num_td_steps: ${num_td_steps}
  num_stacked_frames: ${num_stacked_frames}
  discount: ${discount}
  decay: 0.95
  save_dir: ./replay/

scalar_transform:
  support_min: -2
  support_max: 2
  eps: 1.0e-3

param_opt:
  use_remote: true
  num_gpus: 0.6
  save_interval: 10
  save_dir: ./checkpoints/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: ${env.num_rows}
    obs_cols: ${env.num_cols}
    obs_channels: 44
    repr_rows: 10
    repr_cols: 10
    repr_channels: 64
    dim_action: ${dim_action}
    repr_tower_blocks: 12
    repr_tower_dim: 64
    pred_tower_blocks: 1
    pred_tower_dim: 32
    dyna_tower_blocks: 1
    dyna_tower_dim: 32
    dyna_state_blocks: 1

train:
  # enabled: true
  num_epochs: 1024
  # sample_update_ratio: 20
  batch_size: 1024
  bathces_per_transfer: 16
  lr: 5.0e-2
  weight_decay: 1.0e-4
  update_period: 5
  min_targets_to_train: 5_000
  updates_per_epoch: 32

env_worker:
  num_workers: 4
  num_envs: 64
  num_cpus: 1
  num_gpus: 0.2
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 25
    # output_tree: true
    kwargs:
      dirichlet_alpha: 0.2
      dirichlet_fraction: 0.2
      temperature: 1.0

test_worker:
  interval: 10000
  num_cpus: 0
  num_gpus: 0.2
  planner:
    batch_size: 1
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    kwargs:
      dirichlet_alpha: 0.1
      dirichlet_fraction: 0.1
      temperature: 0.25

reanalyze:
  num_workers: 24
  num_envs: 64
  num_cpus: 1
  num_gpus: 0.2
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    kwargs:
      dirichlet_alpha: 0.1
      dirichlet_fraction: 0.1
