seed: 0
discount: 0.997
num_unroll_steps: 5
num_td_steps: 100
num_stacked_frames: 4
dim_action: 4

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: 10
  num_cols: 10
  num_channels: 6
  known_bound_min: 0
  known_bound_max: 1

replay:
  use_remote: true
  max_size: 1_000_000
  sampling_strategy: hybrid
  num_unroll_steps: ${num_unroll_steps}
  num_td_steps: ${num_td_steps}
  num_stacked_frames: ${num_stacked_frames}
  discount: ${discount}

scalar_transform:
  support_min: -10
  support_max: 10
  eps: 1.0e-3

param_opt:
  use_remote: true
  num_gpus: 0.4
  save_interval: 10
  save_dir: ./checkpoints/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: ${env.num_rows}
    obs_cols: ${env.num_cols}
    obs_channels: 40
    repr_rows: 10
    repr_cols: 10
    repr_channels: 6
    dim_action: ${dim_action}
    repr_tower_blocks: 8
    repr_tower_dim: 6
    pred_tower_blocks: 8
    pred_tower_dim: 6
    dyna_tower_blocks: 8
    dyna_tower_dim: 6
    dyna_state_blocks: 8

# debugging
# nn:
#   arch_cls: moozi.nn.ResNetArchitecture
#   spec_cls: moozi.nn.ResNetSpec
#   spec_kwargs:
#     obs_rows: ${env.num_rows}
#     obs_cols: ${env.num_cols}
#     obs_channels: 40
#     repr_rows: 10
#     repr_cols: 10
#     repr_channels: 2
#     dim_action: ${dim_action}
#     repr_tower_blocks: 2
#     repr_tower_dim: 1
#     pred_tower_blocks: 2
#     pred_tower_dim: 1
#     dyna_tower_blocks: 2
#     dyna_tower_dim: 1
#     dyna_state_blocks: 2

train:
  enabled: true
  num_epochs: 2000
  sample_update_ratio: 1.0
  batch_size: 256
  lr: 5.0e-3
  weight_decay: 5.0e-3

  env_worker:
    num_workers: 6
    num_envs: 5
    num_cpus: 1
    num_gpus: 0.2
    planner:
      num_envs: ${train.env_worker.num_envs}
      dim_action: ${dim_action}
      num_simulations: 10
      dirichlet_alpha: 0.5
      dirichlet_fraction: 0.5
      temperature: 1.0

  reanalyze_worker:
    num_workers: 0
    num_universes: 50
    num_trajs: 1

  test_worker:
    interval: 5
    num_cpus: 1
    num_gpus: 0.2
    planner:
      num_envs: 1
      dim_action: ${dim_action}
      num_simulations: 20
      dirichlet_fraction: 0.2
      dirichlet_alpha: 0.2
      temperature: 0.5
