seed: 0
discount: 0.997
num_unroll_steps: 5
num_td_steps: 5
# TODO: rename num_stakd_frames to history_len or something
num_stacked_frames: 4
dim_action: auto
debug: false

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: auto
  num_cols: auto
  num_channels: auto

replay:
  num_shards: 6
  kwargs:
    use_remote: true
    max_trajs_size: 5_000
    max_targets_size: 300_000
    sampling_strategy: value_diff
    num_unroll_steps: ${num_unroll_steps}
    num_td_steps: ${num_td_steps}
    num_stacked_frames: ${num_stacked_frames}
    discount: ${discount}
    decay: 0.90
    save_dir: ./replay/

scalar_transform:
  support_min: -30
  support_max: 30
  eps: 1.0e-3

param_opt:
  use_remote: true
  num_gpus: 0.6
  save_interval: 10
  save_dir: ./checkpoints/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: ${env.num_rows}
    obs_cols: ${env.num_cols}
    obs_channels: auto
    repr_rows: 10
    repr_cols: 10
    repr_channels: 16
    dim_action: ${dim_action}
    repr_tower_blocks: 6
    repr_tower_dim: 16
    pred_tower_blocks: 1
    pred_tower_dim: 16
    dyna_tower_blocks: 2
    dyna_tower_dim: 16
    dyna_state_blocks: 1

train:
  num_epochs: 500
  update_step_ratio: 2
  batch_size: 1024
  lr: 1.0e-2
  weight_decay: 1.0e-4
  target_update_period: 500
  min_targets_to_train: 1_000
  consistency_loss_coef: 2.0

env_worker:
  num_workers: 30
  num_envs: 16
  num_cpus: 1
  num_gpus: 0.1
  num_steps: 100
  update_period: 1
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 20
    policy_type: gumbel
    # kwargs:
      # dirichlet_alpha: 0.2
      # dirichlet_fraction: 0.2
      # temperature: 1.0

test_worker:
  interval: 5
  num_cpus: 0
  num_gpus: 0.1
  num_trajs: 20
  planner:
    batch_size: 1
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    kwargs:
      dirichlet_alpha: 0.1
      dirichlet_fraction: 0.1
      temperature: 0.25

reanalyze:
  num_workers: 0
  num_envs: 32
  num_cpus: 1
  num_gpus: 0.1
  num_steps: 50
  update_period: 10
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    kwargs:
      dirichlet_alpha: 0.2
      dirichlet_fraction: 0.2
