seed: 0
discount: 0.99
num_unroll_steps: 2
num_td_steps: 5
num_stacked_frames: 2
dim_action: 4

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: 10
  num_cols: 10
  num_channels: 6
  known_bound_min: 0
  known_bound_max: 1

replay:
  use_remote: true
  min_size: 2_000
  max_size: 60_000
  sampling_strategy: ranking
  num_unroll_steps: ${num_unroll_steps}
  num_td_steps: ${num_td_steps}
  num_stacked_frames: ${num_stacked_frames}
  discount: ${discount}

scalar_transform:
  support_min: -10
  support_max: 10
  eps: 1.0e-3

param_opt:
  use_remote: true
  num_gpus: 0.4
  save_interval: 10
  save_dir: ./checkpoints/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: ${env.num_rows}
    obs_cols: ${env.num_cols}
    obs_channels: 20
    repr_rows: 10
    repr_cols: 10
    repr_channels: 64
    dim_action: ${dim_action}
    repr_tower_blocks: 4
    repr_tower_dim: 64
    pred_tower_blocks: 4
    pred_tower_dim: 64
    dyna_tower_blocks: 4
    dyna_tower_dim: 64
    dyna_state_blocks: 4

train:
  enabled: true
  num_epochs: 2000
  sample_update_ratio: 1
  batch_size: 256
  lr: 5.0e-2
  weight_decay: 1.0e-4

  env_worker:
    num_workers: 6
    num_envs: 5
    num_cpus: 1
    num_gpus: 0.2
    planner:
      num_envs: ${train.env_worker.num_envs}
      dim_action: ${dim_action}
      num_simulations: 20
      dirichlet_alpha: 0.2
      dirichlet_fraction: 0.2
      temperature: 1.0

  reanalyze_worker:
    num_workers: 0
    num_universes: 50
    num_trajs: 1

  test_worker:
    interval: 5
    num_cpus: 1
    num_gpus: 0.2
    planner:
      num_envs: 1
      dim_action: ${dim_action}
      num_simulations: 50
      dirichlet_fraction: 0.2
      dirichlet_alpha: 0.2
      temperature: 0.5
