seed: 0
discount: 0.99
num_unroll_steps: 5
num_td_steps: 5
# TODO: rename num_stakd_frames to history_len or something
num_stacked_frames: 4
dim_action: auto
debug: false

env:
  name: MinAtar:SpaceInvaders-v1
  num_rows: auto
  num_cols: auto
  num_channels: auto

replay:
  num_shards: 4
  kwargs:
    use_remote: true
    max_trajs_size: 2_000
    max_targets_size: 1_000_000
    sampling_strategy: value_diff
    num_unroll_steps: ${num_unroll_steps}
    num_td_steps: ${num_td_steps}
    num_stacked_frames: ${num_stacked_frames}
    discount: ${discount}
    decay: 0.97
    save_dir: ./replay/

scalar_transform:
  support_min: -3
  support_max: 3
  eps: 1.0e-3

param_opt:
  use_remote: true
  num_gpus: 0.6
  save_interval: 10
  save_dir: ./checkpoints/

nn:
  arch_cls: moozi.nn.ResNetArchitecture
  spec_cls: moozi.nn.ResNetSpec
  spec_kwargs:
    obs_rows: ${env.num_rows}
    obs_cols: ${env.num_cols}
    obs_channels: auto
    repr_rows: 10
    repr_cols: 10
    repr_channels: 48
    dim_action: ${dim_action}
    repr_tower_blocks: 6
    repr_tower_dim: 48
    pred_tower_blocks: 1
    pred_tower_dim: 48
    dyna_tower_blocks: 1
    dyna_tower_dim: 48
    dyna_state_blocks: 1

train:
  num_epochs: 1024
  steps_to_update_once: 512
  batch_size: 1024
  lr: 3.0e-2
  weight_decay: 1.0e-4
  target_update_period: 500
  min_targets_to_train: 5_000
  consistency_loss_coef: 2.0

env_worker:
  num_workers: 40
  num_envs: 16
  num_cpus: 1
  num_gpus: 0.1
  num_steps: 50
  update_period: 10
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 20
    kwargs:
      dirichlet_alpha: 0.2
      dirichlet_fraction: 0.2
      temperature: 1.0

test_worker:
  interval: 1
  num_cpus: 0
  num_gpus: 0.2
  num_trajs: 1
  planner:
    batch_size: 1
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    output_tree: true
    limit_depth: true
    kwargs:
      dirichlet_alpha: 0.1
      dirichlet_fraction: 0.1
      temperature: 0.25

reanalyze:
  num_workers: 0
  num_envs: 64
  num_cpus: 1
  num_gpus: 0.2
  num_steps: 30
  update_period: 5
  planner:
    dim_action: ${dim_action}
    discount: ${discount}
    num_unroll_steps: ${num_unroll_steps}
    num_simulations: 50
    kwargs:
      dirichlet_alpha: 0.2
      dirichlet_fraction: 0.2
